### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by ylogx** [pulug/sfd15#1]

**Comment by ylogx** [comment]
AFAICT this should be working, the dns is all correctly pointed @Ashish-Bansal

**Comment by Ashish-Bansal** [comment]
Actually I forgot to remove CNAME from pulug/sfd14 before adding CNAME to pulug/sfd15. I realized this later on and then I removed CNAME from pulug/sfd14.

Although I am not sure but we can try removing and adding CNAME again to pulug/sfd15.

**Comment by Ashish-Bansal** [comment]
Fixed by adding CNAME again.
